### ISSUE TITLE
Problem with QGIS 3.8.3 - Zanzibar

### ISSUE THREAD

**Issue by woody23** [Hacked-Crew/Magnetic-Declination#4]
I installed the plugin, version 2.0.1 in QGIS. When I open it, it only shows a small screen and ity is not possible to enlarge it, in order to do the necessary inputs or use any of the buttons. I can however switch between the different tabs and move up and down in the tabs. However, this is not possible in the calculate-tab, which in this small format looks very messy, all information in this screen is present, but in a very chaotic unusable way
![plugin](https://user-images.githubusercontent.com/19713673/69532130-76fb6a80-0f75-11ea-80c5-a6d26a8f7628.png)

**Comment by Hacked-Crew** [comment]
Hello,
strange things! Same version in **QGIS 3.4.12 Madeira** works well.
Thank You, I’ll have to check with the new QGIS versions.

**Comment by Hacked-Crew** [comment]
I cannot reproduce the error.
greetings
