### ISSUE TITLE
TypeError:QgsRubberBand():argument 'geometryType' has unexpected type 'int'

### ISSUE THREAD

**Issue by kc9eye** [Hacked-Crew/Magnetic-Declination#7]
When trying to draw the compass on the map after calculating the declination. This error occurs and will not draw the compass. This error occurs every time, no matter the map. Declination can be calculated, but the compass can not be draw on the map.
![Untitled](https://github.com/Hacked-Crew/Magnetic-Declination/assets/7613798/e2ce9f9e-6749-4a14-8262-b1071c80037d)

**Comment by Flushot** [comment]
@kc9eye This was fixed in https://github.com/Hacked-Crew/Magnetic-Declination/pull/5

**Comment by Hacked-Crew** [comment]
added backward and foreward rubberband compatibility.
